THRESHOLDS_VERSION = "1.0.0"

MIN_SAMPLES_P50 = 20
MIN_SAMPLES_P90 = 30
MIN_SAMPLES_LOCATION_P50 = 10
MIN_SAMPLES_WEEKLY_P50 = 5
MIN_RATE_DENOMINATOR = 30
MIN_RATE_EVENTS = 5
CHANGE_MIN_RELATIVE = 0.10
BOOTSTRAP_ITERATIONS = 1000
BOOTSTRAP_CI = 0.90

N_DAYS_MERGED = 3
MIN_LOCATION_PRS = 10
MAX_LOCATIONS_IN_SNAPSHOT = 15
DIRECTORY_LOCATIONS_PER_PR = 3

AT_RISK_WARNING_PERCENTILE = 85
AT_RISK_CRITICAL_PERCENTILE = 95
AT_RISK_BASELINE_DAYS = 90
AT_RISK_FALLBACK_DAYS = 180
AT_RISK_MIN_BASELINE = 30
AT_RISK_DEFAULT_HOURS = {
    "waiting_reviewer": 48.0,
    "waiting_author": 72.0,
    "waiting_ci": 6.0,
    "waiting_merge": 24.0,
}
AT_RISK_MAX_ITEMS = 20

WHAT_IF_TARGET_HOURS = {"pickup": 8.0, "merge": 8.0, "ci": 2.0}
REVIEW_CONCENTRATION_TOP_K = 2
LARGE_PR_LINES = 500
FAST_APPROVAL_MINUTES = 10
FAST_APPROVAL_MIN_LINES = 300
LATE_REJECTION_DAYS = 14
LATE_REJECTION_ROUNDS = 2
SUPERSEDE_WINDOW_DAYS = 14
SIZE_BUCKETS = ((10, "XS"), (100, "S"), (500, "M"), (1000, "L"))
CI_COVERAGE_MIN = 0.5
REVIEW_CAPACITY_PICKUP_RATIO = 1.5
REVIEW_CAPACITY_MIN_WAIT_SHARE = 0.15
REVIEW_CAPACITY_HIGH_WAIT_SHARE = 0.30
QUEUE_GROWTH_WEEK_SHARE = 0.5
QUEUE_GROWTH_MIN_UNSERVED_SHARE = 0.20
QUEUE_GROWTH_HIGH_UNSERVED_SHARE = 0.50
CONCENTRATION_SHARE = 0.60
CONCENTRATION_HIGH_SHARE = 0.75
MERGE_BLOCKED_SHARE = 0.15
MERGE_BLOCKED_HIGH_SHARE = 0.30
MERGE_BLOCKED_P50_HOURS = 24.0
CI_WAIT_SHARE = 0.15
CI_WAIT_HIGH_SHARE = 0.30
REWORK_ROUNDS = 2.5
REWORK_POST_REVIEW_SHARE = 0.5
WASTE_SHARE = 0.15
WASTE_HIGH_SHARE = 0.25
LOST_WHILE_WAITING_MIN = 5
GUARDRAIL_REVERT_RATE_DELTA = 0.01
EXTERNAL_PICKUP_RATIO = 2.0
