"""Static evidence catalog: the snapshot metrics exposed to the narrative as numbered E-IDs.

Rows are (ID, key, label, JSON pointer, unit, side). IDs are stable and sparse: removed metrics
leave gaps rather than renumbering. evidence.py adds location items (E51-E70) at runtime.
"""

CATALOG = (
    (
        "E1",
        "cycle_time_p50",
        "Median cycle time",
        "/efficiency/cycle_time_p50_hours",
        "hours",
        "efficiency",
    ),
    ("E3", "merged_prs", "Merged PRs", "/efficiency/merged_prs", "count", "efficiency"),
    (
        "E8",
        "avg_review_rounds",
        "Average review rounds per merged PR",
        "/efficiency/avg_review_rounds",
        "rounds",
        "efficiency",
    ),
    (
        "E9",
        "post_review_commit_share",
        "Share of merged PRs with commits after the first review",
        "/efficiency/post_review_commit_share",
        "share",
        "efficiency",
    ),
    (
        "E15",
        "pickup_p50",
        "Median wait for the first review",
        "/efficiency/pickup_p50_hours",
        "hours",
        "bottleneck",
    ),
    (
        "E18",
        "ledger_waiting_reviewer",
        "Share of PR time waiting on reviewers",
        "/time_ledger/states/waiting_reviewer",
        "share",
        "bottleneck",
    ),
    (
        "E19",
        "ledger_waiting_author",
        "Share of PR time waiting on authors",
        "/time_ledger/states/waiting_author",
        "share",
        "bottleneck",
    ),
    (
        "E20",
        "ledger_waiting_ci",
        "Share of PR time waiting on CI",
        "/time_ledger/states/waiting_ci",
        "share",
        "bottleneck",
    ),
    (
        "E21",
        "ledger_waiting_merge",
        "Share of PR time waiting to merge after approval",
        "/time_ledger/states/waiting_merge",
        "share",
        "bottleneck",
    ),
    (
        "E22",
        "queue_weeks_imbalanced",
        "Weeks in which review demand exceeded first reviews",
        "/bottleneck_analysis/review_queue/weeks_inflow_exceeds_outflow",
        "count",
        "bottleneck",
    ),
    (
        "E24",
        "review_concentration",
        "Share of reviews done by the top K reviewers",
        "/efficiency/review_concentration_top_k",
        "share",
        "bottleneck",
    ),
    (
        "E30",
        "pr_size_p50",
        "Median PR size",
        "/efficiency/pr_size_p50_lines",
        "lines",
        "bottleneck",
    ),
    (
        "E31",
        "large_pr_share",
        "Share of merged PRs with 500 or more changed lines",
        "/efficiency/large_pr_share",
        "share",
        "bottleneck",
    ),
    (
        "E37",
        "attr_waiting_reviewer_increase",
        "Share of the added time spent waiting on reviewers",
        "/trend/attribution/states/waiting_reviewer/share_of_increase",
        "share",
        "bottleneck",
    ),
    (
        "E39",
        "attr_waiting_ci_increase",
        "Share of the added time spent waiting on CI",
        "/trend/attribution/states/waiting_ci/share_of_increase",
        "share",
        "bottleneck",
    ),
    (
        "E42",
        "attr_large_prs_increase",
        "Share of the added cycle time coming from PRs with 500+ lines",
        "/trend/attribution/large_prs/share_of_increase",
        "share",
        "bottleneck",
    ),
    (
        "E44",
        "ci_queue_p50",
        "Median CI queue time",
        "/bottleneck_analysis/ci/queue_p50_minutes",
        "minutes",
        "bottleneck",
    ),
    (
        "E45",
        "ci_run_p50",
        "Median CI run time",
        "/bottleneck_analysis/ci/run_p50_minutes",
        "minutes",
        "bottleneck",
    ),
    (
        "E46",
        "ci_flaky_rerun_rate",
        "Share of CI runs that passed only on a rerun",
        "/bottleneck_analysis/ci/flaky_rerun_rate",
        "share",
        "bottleneck",
    ),
    (
        "E48",
        "slowest_decile_size_ratio",
        "Median size of the slowest 10% of PRs vs the rest",
        "/drivers/slowest_decile_size_ratio",
        "ratio",
        "bottleneck",
    ),
)
