"""Static evidence catalog: the snapshot metrics exposed to the narrative as numbered E-IDs.

Rows are (ID, key, label, JSON pointer, unit, side). evidence.py adds location items (E51-E70)
and top-finding items (E71-E73) at runtime, and resolves the {i} index in the E48 pointer.
"""

CATALOG = (
    (
        "E1",
        "cycle_time_p50",
        "Median cycle time",
        "/efficiency/cycle_time_p50_hours",
        "hours",
        "efficiency",
    ),
    (
        "E2",
        "cycle_time_p90",
        "90th percentile cycle time",
        "/efficiency/cycle_time_p90_hours",
        "hours",
        "efficiency",
    ),
    ("E3", "merged_prs", "Merged PRs", "/efficiency/merged_prs", "count", "efficiency"),
    (
        "E4",
        "effective_throughput",
        "Effective throughput (merged PRs minus reverted and revert PRs)",
        "/efficiency/effective_throughput",
        "count",
        "efficiency",
    ),
    (
        "E5",
        "merged_within_n_days",
        "Share of ready PRs merged within N days",
        "/efficiency/merged_within_n_days",
        "share",
        "efficiency",
    ),
    (
        "E6",
        "waiting_share",
        "Share of cycle time spent waiting on reviewers, CI or merge",
        "/efficiency/waiting_share",
        "share",
        "efficiency",
    ),
    (
        "E7",
        "waste_share",
        "Share of finished PRs wasted (closed unmerged or reverted)",
        "/efficiency/waste_share",
        "share",
        "efficiency",
    ),
    (
        "E8",
        "avg_review_rounds",
        "Average review rounds per merged PR",
        "/efficiency/avg_review_rounds",
        "rounds",
        "efficiency",
    ),
    (
        "E9",
        "post_review_commit_share",
        "Share of merged PRs with commits after the first review",
        "/efficiency/post_review_commit_share",
        "share",
        "efficiency",
    ),
    ("E10", "revert_rate", "Revert rate", "/efficiency/revert_rate", "share", "efficiency"),
    (
        "E11",
        "within_hist_p85",
        "Share of merged PRs finished within the historical p85",
        "/efficiency/predictability/within_hist_p85",
        "share",
        "efficiency",
    ),
    (
        "E12",
        "weekly_throughput_cv",
        "Week-to-week variation of merged PRs",
        "/efficiency/predictability/weekly_throughput_cv",
        "coefficient",
        "efficiency",
    ),
    (
        "E13",
        "survival_median",
        "Median ready-to-merge time including open PRs",
        "/efficiency/survival/current/median_hours",
        "hours",
        "efficiency",
    ),
    (
        "E14",
        "coding_p50",
        "Median coding time",
        "/efficiency/stage_p50_hours/coding",
        "hours",
        "bottleneck",
    ),
    (
        "E15",
        "pickup_p50",
        "Median wait for the first review",
        "/efficiency/stage_p50_hours/pickup",
        "hours",
        "bottleneck",
    ),
    (
        "E16",
        "review_p50",
        "Median time from first review to approval",
        "/efficiency/stage_p50_hours/review",
        "hours",
        "bottleneck",
    ),
    (
        "E17",
        "merge_p50",
        "Median time from approval to merge",
        "/efficiency/stage_p50_hours/merge",
        "hours",
        "bottleneck",
    ),
    (
        "E18",
        "ledger_waiting_reviewer",
        "Share of PR time waiting on reviewers",
        "/time_ledger/states/waiting_reviewer",
        "share",
        "bottleneck",
    ),
    (
        "E19",
        "ledger_waiting_author",
        "Share of PR time waiting on authors",
        "/time_ledger/states/waiting_author",
        "share",
        "bottleneck",
    ),
    (
        "E20",
        "ledger_waiting_ci",
        "Share of PR time waiting on CI",
        "/time_ledger/states/waiting_ci",
        "share",
        "bottleneck",
    ),
    (
        "E21",
        "ledger_waiting_merge",
        "Share of PR time waiting to merge after approval",
        "/time_ledger/states/waiting_merge",
        "share",
        "bottleneck",
    ),
    (
        "E22",
        "queue_weeks_imbalanced",
        "Weeks in which review demand exceeded first reviews",
        "/bottleneck_analysis/review_queue/weeks_inflow_exceeds_outflow",
        "count",
        "bottleneck",
    ),
    (
        "E23",
        "queue_unserved_share",
        "Share of this period's review demand not yet served",
        "/bottleneck_analysis/review_queue/net_inflow_share",
        "share",
        "bottleneck",
    ),
    (
        "E24",
        "review_concentration",
        "Share of reviews done by the top K reviewers",
        "/efficiency/review_concentration_top_k",
        "share",
        "bottleneck",
    ),
    (
        "E25",
        "at_risk_total",
        "Open PRs waiting longer than usual",
        "/at_risk_summary/total",
        "count",
        "bottleneck",
    ),
    (
        "E26",
        "at_risk_top_location_share",
        "Share of reviewer-waiting at-risk PRs in the top location",
        "/signals/at_risk_reviewer_top_location_share",
        "share",
        "bottleneck",
    ),
    (
        "E27",
        "external_pickup_ratio",
        "First-review wait of external vs internal contributors",
        "/signals/external_pickup_ratio",
        "ratio",
        "bottleneck",
    ),
    (
        "E28",
        "second_approval_share",
        "Share of approved PRs with a second approval",
        "/bottleneck_analysis/merge_blockers/second_approval_share",
        "share",
        "bottleneck",
    ),
    (
        "E29",
        "post_approval_update_share",
        "Share of approved PRs updated after approval",
        "/bottleneck_analysis/merge_blockers/post_approval_update_share",
        "share",
        "bottleneck",
    ),
    (
        "E30",
        "pr_size_p50",
        "Median PR size",
        "/efficiency/pr_size_p50_lines",
        "lines",
        "bottleneck",
    ),
    (
        "E31",
        "large_pr_share",
        "Share of merged PRs with 500 or more changed lines",
        "/signals/large_pr_share",
        "share",
        "bottleneck",
    ),
    (
        "E32",
        "fast_large_approval_share",
        "Share of merged PRs with 300+ lines approved within 10 minutes without feedback",
        "/signals/fast_large_approval_share",
        "share",
        "bottleneck",
    ),
    (
        "E33",
        "merged_without_approval_share",
        "Share of merged PRs merged without approval",
        "/signals/merged_without_approval_share",
        "share",
        "bottleneck",
    ),
    (
        "E34",
        "lost_while_waiting",
        "PRs closed while waiting for review",
        "/waste/lost_while_waiting",
        "count",
        "efficiency",
    ),
    ("E35", "late_rejections", "Late rejections", "/waste/late_rejections", "count", "efficiency"),
    (
        "E36",
        "cycle_mean",
        "Mean cycle time per merged PR",
        "/trend/attribution/cycle_mean_hours/current",
        "hours",
        "efficiency",
    ),
    (
        "E37",
        "attr_waiting_reviewer_increase",
        "Share of the added time spent waiting on reviewers",
        "/trend/attribution/states/waiting_reviewer/share_of_increase",
        "share",
        "bottleneck",
    ),
    (
        "E38",
        "attr_waiting_author_increase",
        "Share of the added time spent waiting on authors",
        "/trend/attribution/states/waiting_author/share_of_increase",
        "share",
        "bottleneck",
    ),
    (
        "E39",
        "attr_waiting_ci_increase",
        "Share of the added time spent waiting on CI",
        "/trend/attribution/states/waiting_ci/share_of_increase",
        "share",
        "bottleneck",
    ),
    (
        "E40",
        "attr_waiting_merge_increase",
        "Share of the added time spent waiting to merge",
        "/trend/attribution/states/waiting_merge/share_of_increase",
        "share",
        "bottleneck",
    ),
    (
        "E41",
        "attr_coding_increase",
        "Share of the added time spent coding",
        "/trend/attribution/states/coding/share_of_increase",
        "share",
        "bottleneck",
    ),
    (
        "E42",
        "attr_large_prs_increase",
        "Share of the added cycle time coming from PRs with 500+ lines",
        "/trend/attribution/large_prs/share_of_increase",
        "share",
        "bottleneck",
    ),
    (
        "E43",
        "attr_waiting_reviewer_decrease",
        "Share of the saved time coming from less waiting on reviewers",
        "/trend/attribution/states/waiting_reviewer/share_of_decrease",
        "share",
        "bottleneck",
    ),
    (
        "E44",
        "ci_queue_p50",
        "Median CI queue time",
        "/bottleneck_analysis/ci/queue_p50_minutes",
        "minutes",
        "bottleneck",
    ),
    (
        "E45",
        "ci_run_p50",
        "Median CI run time",
        "/bottleneck_analysis/ci/run_p50_minutes",
        "minutes",
        "bottleneck",
    ),
    (
        "E46",
        "ci_flaky_rerun_rate",
        "Share of CI runs that passed only on a rerun",
        "/bottleneck_analysis/ci/flaky_rerun_rate",
        "share",
        "bottleneck",
    ),
    (
        "E47",
        "ci_coverage",
        "Share of merged PRs with CI data",
        "/time_ledger/ci_coverage",
        "share",
        "bottleneck",
    ),
    (
        "E48",
        "slowest_decile_size_ratio",
        "Median size of the slowest 10% of PRs vs the rest",
        "/drivers/slowest_decile/features/{i}/ratio",
        "ratio",
        "bottleneck",
    ),
    (
        "E49",
        "unassigned_pickup_ratio",
        "First-review wait without vs with requested reviewers",
        "/drivers/assignment/ratio",
        "ratio",
        "bottleneck",
    ),
    (
        "E50",
        "re_review_wait_p50",
        "Median wait for a re-review",
        "/drivers/review_round_cost/re_review_wait_p50_hours",
        "hours",
        "bottleneck",
    ),
)
